# https://github.com/docker-library/gcc/issues/57
# use debian images here

stages:
  - build
  - test
  - container

build-code:
  stage: build
  before_script:
    - apt update
    - apt install -y cmake make build-essential libboost-all-dev
  script:
    - mkdir build
    - pushd build
    - VERBOSE=1 cmake ..
    - make
    - popd
  artifacts:
    when: always
    paths:
      - ./build/
  tags:
    - bullseye

linter:
  stage: build
  before_script:
    - apt update
    - apt install -y clang-format
  script:
    - clang-format -style=file --dry-run --Werror src/*.hpp src/*.cpp
  artifacts:
    when: always
    paths:
      - ./build/
  tags:
    - bullseye

test-code:
  stage: test
  before_script:
    - apt update
    - apt-get update
  script:
    - echo ""
  dependencies:
    - build-code
  tags:
    - bullseye

build-container:
  stage: container
#  before_script:
#    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} docker.io
  script:
    - cd ./docker && ./build-and-push.sh && cd ..
  dependencies:
    - build-code
  tags:
    - shell
